#+TITLE:     Apuntes de Electricidad y Magnetismo - Grado en Ing. de Materiales
#+STARTUP: indent
#+STARTUP: latexpreview
#+SETUPFILE: config.org
#+OPTIONS: H:3
#+OPTIONS: tex:t
#+PROPERTY: header-args :results output :exports both :session R:apuntes :tangle yes :comments org

* 
** ¿Qué es R?
*** ¿Qué es =R=?						    
Es un entorno de programación orientado al cálculo, manipulación de datos, y representación gráfica, publicado como software libre con licencia GNU-GPL.
#+BEGIN_CENTER
 [[http://www.R-project.org]] 
#+END_CENTER


** Trabajo de un campo de fuerza

Lo que nos importa es la dirección de la fuerta sobre la trayectoria de la partícula. Utilizamos el concepto de variación diferencial de posición (con el vector r, con respecto a un sistema de referencia, y diferencial de r es el increemento infinitesimal de ese vector). Para un desplazamiento pequeño diferencial, si multiplicamos F.dr e integramos entre el punto inicial (A) y final (B) ese es el trabajo de un campo de fuerza sobre la partícula de un punto a otro. 

Una partícula sobre la cual no se ejerce ninguna fuerza no se acelera (2ª ley de Newton). 

Cuando la partícula se mueve de un punto a otro hay una pequeña variación infinitesimal (dr)

Si yo diferencio (es decir, veo como es esta magnitud cuando hay una variación infinetesimal). 

El incremento diferencial de la energía lo puedo obtener olvidándome con respecto a que estoy derivando. 

Derivada del primero por el primeoro sin derivar y derivada del segundo por el primero sin derivar. Pon

*** Campos de fuerzas conservativos

En cierto campos de fuerza, el trabajo no depende de la trayectoria que siga la partícula. En estos casos, se cumple que existe un campo escalar, que llamamos energía potencial E, tal que Fvect = -grad Epot. 

Para este tipo de campos de fuerza, por tanto, 

(insertar apuntes pizarra). 

**** Campo eléctrico como campo de fuerza conservativo: 

Si queremos calcular ahora el trabajo que realiza el campo de fuerza eléctrica (igual al campo y la carga que tenga la partícula). Si el campo electrico lo podemos escribir como el gradiente 


El campo total en un punto es la suma de la carga eléctrica de las cargas individuales. Para cada una 

(ver fotos de la pizrra) 

- Si el desplazamiento tiene exactamente la dirección radial, el campo E tendría el máximo valor (puesto que los dos vectores tendrían el mismo sentido): 
- Si el desplazamiento tiene dirección perpendicular, el campo E sería 0, el campo E tendría una contribución nula, puesto que el producto escalar sería 0. 

Al desplazarnos de un punto otro, 

(ver foto de la pizarra). 

POr tanto, al desplazarnos entre dos puntos, en el campo de las cargas eléctricas vamos a hablar del campo ecalar V (equivalente a Energía potencial). 

(ver foto de la pizarra).

Por tanto, si definimos el campo escalar V =.. se tiene que dv = -ke q/r2dr = -Edr 

Por tanto, para calcular el trabajo de la fuerza eléctrica, 

para el campo electrico que crea cada carga, podemos escribir la funcion escalar potencial electrico....

El potencial electrico entonces V (que nos ha aparecido analizando una carga electrica en concreto), da lugar a un potencial electrico total, 


\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures
\end{equation}                          % etc

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].

