#+TITLE:     Apuntes de Electricidad y Magnetismo - Grado en Ing. de Materiales
#+STARTUP: indent
#+STARTUP: latexpreview
#+SETUPFILE: config.org
#+OPTIONS: H:3
#+OPTIONS: tex:t
#+PROPERTY: header-args :results output :exports both :session R:apuntes :tangle yes :comments org

#+LaTeX_+HEADER: \usepackage{siunitx} 

* 
** ¿Qué es R?
*** ¿Qué es =R=?						    
Es un entorno de programación orientado al cálculo, manipulación de datos, y representación gráfica, publicado como software libre con licencia GNU-GPL.
#+BEGIN_CENTER
 [[http://www.R-project.org]] 
#+END_CENTER


** Trabajo de un campo de fuerza

Lo que nos importa es la dirección de la fuerta sobre la trayectoria de la partícula. Utilizamos el concepto de variación diferencial de posición (con el vector r, con respecto a un sistema de referencia, y diferencial de r es el increemento infinitesimal de ese vector). Para un desplazamiento pequeño diferencial, si multiplicamos F.dr e integramos entre el punto inicial (A) y final (B) ese es el trabajo de un campo de fuerza sobre la partícula de un punto a otro. 

Una partícula sobre la cual no se ejerce ninguna fuerza no se acelera (2ª ley de Newton). 

Cuando la partícula se mueve de un punto a otro hay una pequeña variación infinitesimal (dr)

Si yo diferencio (es decir, veo como es esta magnitud cuando hay una variación infinetesimal). 

El incremento diferencial de la energía lo puedo obtener olvidándome con respecto a que estoy derivando. 

Derivada del primero por el primeoro sin derivar y derivada del segundo por el primero sin derivar. Pon

*** Campos de fuerzas conservativos

En cierto campos de fuerza, el trabajo no depende de la trayectoria que siga la partícula. En estos casos, se cumple que existe un campo escalar, que llamamos energía potencial E, tal que Fvect = -grad Epot. 

Para este tipo de campos de fuerza, por tanto, 

(insertar apuntes pizarra). 

**** Campo eléctrico como campo de fuerza conservativo: 

Si queremos calcular ahora el trabajo que realiza el campo de fuerza eléctrica (igual al campo y la carga que tenga la partícula). Si el campo electrico lo podemos escribir como el gradiente 


El campo total en un punto es la suma de la carga eléctrica de las cargas individuales. Para cada una 

(ver fotos de la pizrra) 

- Si el desplazamiento tiene exactamente la dirección radial, el campo E tendría el máximo valor (puesto que los dos vectores tendrían el mismo sentido): 
- Si el desplazamiento tiene dirección perpendicular, el campo E sería 0, el campo E tendría una contribución nula, puesto que el producto escalar sería 0. 

Al desplazarnos de un punto otro, 

(ver foto de la pizarra). 

POr tanto, al desplazarnos entre dos puntos, en el campo de las cargas eléctricas vamos a hablar del campo ecalar V (equivalente a Energía potencial). 

(ver foto de la pizarra).

Por tanto, si definimos el campo escalar V =.. se tiene que dv = -ke q/r2dr = -Edr 

Por tanto, para calcular el trabajo de la fuerza eléctrica, 

para el campo electrico que crea cada carga, podemos escribir la funcion escalar potencial electrico....

El potencial electrico entonces V (que nos ha aparecido analizando una carga electrica en concreto), da lugar a un potencial electrico total, 


Recapitulando, para F conservativa... 


Podemos pensar en superficies en las que el potencial eléctrico es constante. 


(ver pizarar). 

Para una pa de una partícula cargada bajo la acción de un campo eléctrico 

V: potencial que crea el resto de cargas que hay en el espacio. 
PAra calcular el potencial, si tenemos varis, sería igual al sumatorio de las cargas. 
Si tuvieramos una distribución de cargas, tendríamos que integrar. 
Si tuvieramos un volumen integraríasmo sobre el volumen .... 


$x^2$

$x=\sqrt{b}$


\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures
\end{equation}                          % etc

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].


Gustavo resuleve el ejercicio. 


Ejercicio 2.2 

Desde el punto de vista físico, hay que saber que hay que calcular el potencial según 

$V=\in_A^B k_e \frac{\lambda dl}{r} = $ 

Matemáticamente, vamos a ver a qué es igual a cada parte. Vamos a ver si puedo integrar en función de la variable x. Intentemos escribir r y dl en funcion d el variable x. 

La distancia r al origen es muy facil, sería $r=\sqrt(x^2+y^2)=\sqrt(x^2+((\frac{a}{x})^2 $

Y el diferencial de longitud, viene dado por $dl=\sqrt(dx^2+dy^2)=\sqrt(dx^2(1+dy/dx^2)=$

$y^{'}=\frac{dx}{dy} = \frac{d}{x}\frac{a^2}{x}=-\frac{a^2}{x^2}$

$V= \int_{x=a}^{x=2a} k_e\frac{\lambda dx \sqrt (1+\frac{-a^2}{x^2}}){\sqrt(x^2+(\frac{a^2}{x})^2}$


Siguiente clase 

*** Ejemplo: Potencial eléctrico V que varía linealmente entre dos planos separados por una distancia d. 



Conocemos el potencial eléctrico V y queremos calcular el campo eléctrico (E = -grad V)

Ejempplo: Tenemos dos planos en los que conocemos el potencial eléctrico (V2>V1, por lo que aumenta linearmente en la cordneada z) 

___________________ $V_2$  

___________________ $V_1$

1. Escribimos el potencial 

$V = V_1 + \frac{V2-V1}{d} z 

Caclculamos el campo eléctrico 

$\vec{E} =-\vec{grad} V = - \lgroup \frac{\partial V }{\partial x} \hat{u_x} + \frac{\partial V }{\partial y} \hat{u_y} + \frac{\partial V }{\partial z} \hat{u_z}  \rgroup =  - \lgroup 0 + \frac{\partial V }{\partial z} \hat{u_z}  = -\frac{\partial  }{\partial z} \lgroup V_1 +  \frac{V_2 - V_1 }{d}z \hat{u_z}  = - \frac{V_2 - V_1 }\hat{u_z}$

Podemos preguntarnos, ¿qué ocurriría con una cierta partícula cargada que pusiéramos en el esapcio entre los planos? 
¿Seríais capaz de calcular como varia la velocidad de la partícula al pasar del punto A al B, de masa mp y carga qp, partiendo del reposo? 

Al ser un campo eléctrico conservativo, 

$E_c + E_p = constante $ 

$\Delta E_c = - \Delta E_p$ 

$E_{c,B}-E_{c,A} = -(E_{p,B}-E_{p,A})$

$1/2 m_p v_B^2 - 1/2 m 0^2 = - (q_p V_B - q_p V_A) $

$v_b = \sqrt (\frac{2}{m_p} (q_p V_a - q_p V_B) ) = \sqrt (\frac{2 q_p}{m_p} (V_a - V_B) ) = \sqrt (\frac{2 q_p}{m_p} \frac{(V_2 - V_1)}{d}l)  $

$V_A-V_B = (V_1 + \frac{V_2 -V_1}{d} z_A) - (V_1 + \frac{V_2 -V_1}{d} z_B) = \frac{V_2 - V_1}{d}l $

Esto es lo que encontramos cuando tenemos dos conductores (le llamamos un condensador)

$\vec{F} = q_p\vec{E} $ 

$m\vec{a} =\vec{F} =  q_p\vec{E} $ 


** Gradiente de $\vec{E}$ en casos de interés

*** (a) Si $\rho$ solo dpende de z 

$E(z) = E_z (z) \hat{u_z}$

$E = - \vec{grad} (V) = - \frac{\partial V(z)}{\partial z} \hat{u_z} $ 

El campo eléctrico $\vec{E}$ sólo tiene componente según z, $V$ solo puede depender de z, $V(z) 



*** (b) Distribución de carga con simetría esférica: $\rho$ solo depende de $r$:

El campo eléctrico es perpendicular a las superficies en las que V es constante (i.e. superficies esféricas). 

$\vec{E} = E_(r) \hat{u_r}$ 

$E = - \vec{grad} (V) = - \frac{\partial V}{\partial zr} \hat{u_r} $ 


*** (c) Distribución de carga con eje de simetría de revolución, $\rho$ sólo dpende de la distancia $r$ al eje 


$\vec{E} = E(r) \hat{u_r} = -\vec{grad} (V) = - \frac{\partial V}{\partial r} \hat{u_r} $ 

El potencial $V$ sólo depende de la distancia r 


** Cálculo del potencial V a partir del campo eléctrico $\vec{E}$

Lo que varía cualquier función escalar es su gradiente multipiplicaod por su vector de posición . Podemos ver fácilmente cuál es la diferencia de potencial entre dos campos cualesquiera basándonos en esta expresión diferencial. 

$\vec{E} = -\vec{grad} (V)$ 

$dV = \vec{grad} (V) \cdot \vec{d}r  = \vec{E} \cdot  \vec{d}r $ 

Entre dos puntos A y B, el potencial 

$V_B - V_A = \int_A^B dV = \int_A^B - \vec{E} \cdot  \vec{d}r  $

Paréntesis, hemos visto que para una carga puntal q: 

$V = k_e \frac{q}{r} = \frac{1}{4 \pi \epsilon_0} \frac{q}{r} $ 

Luego 

En el caso de distribución de carga de tañao finito, al ser V=0 en $\inf$: 

$V_P = V_P - 0 = \int_{\inf}^P \vec{E} \cdot  \vec{d}r  $

En este caso, 

$V_B - V_A = \int_A ^B -\vec{E} \cdot \vec{d}r  $ 

**** Ejemplo: recta uniformemente cargada con densidad lineal $\lambda$ 

No podemos decir que la recta tiene un potencial 0 en el infinito, porque la recta llega hasta el inifnito. 

Puedo calcular la diferencial de potencial entre los puntos a la distancia $r_a$ y $r_b$

$\vec{E} = \frac{\lambda}{2 \pi \epsilon_0 r \hat{u_r}} = $ 

= \int_A^B = -\frac{\lambda}{2 \pi \epsilon_0 r} dr = -\frac{\lambda}{2 \pi \epsilon_0 r} \int_A^B \frac{dr}{r} = \frac{\lambda}{2 \pi \epsilon_0 r} ln r _{r_A}^{r_B} =$ 

$= -\frac{\lambda}{2 \pi \epsilon_0 r} (ln (r_b) - ln (r_a)) = - \frac{\lambda}{2 \pi \epsilon_0 r} ln (\frac{r_B}{r_A})


**** Ejemplo: Esfera uniformemente cargada, con densidad de carga volumétrica $\rho$, de radio R 

¿Cómo calcular la diferencia de potencial entre varios puntos?

Aquí sí podemos tomar como origen de potenciales el infinito V = 0 (la carga está contenida en un volumen).  

$V_p = int_{inf}^P - \vec{E} \cdot \vec{dr} $ 

Hemos obtenido que 

$E = \frac{1}{4 \pi \epsilon _0} \frac{4/3 \pi \R^3 \rho}{r^2} \hat{u_r} $ si r>R

$E = \frac{\rho r}{3 \epsilon_0}\hat{u_r} $ si r<=R

