#+TITLE:     Apuntes de Electricidad y Magnetismo - Grado en Ing. de Materiales
#+STARTUP: indent
#+STARTUP: latexpreview
#+SETUPFILE: config.org
#+OPTIONS: H:3
#+OPTIONS: tex:t
#+PROPERTY: header-args :results output :exports both :session R:apuntes :tangle yes :comments org

#+LaTeX_+HEADER: \usepackage{siunitx} 

* 
** ¿Qué es R?
*** ¿Qué es =R=?						    
Es un entorno de programación orientado al cálculo, manipulación de datos, y representación gráfica, publicado como software libre con licencia GNU-GPL.
#+BEGIN_CENTER
 [[http://www.R-project.org]] 
#+END_CENTER


** Trabajo de un campo de fuerza

Lo que nos importa es la dirección de la fuerta sobre la trayectoria de la partícula. Utilizamos el concepto de variación diferencial de posición (con el vector r, con respecto a un sistema de referencia, y diferencial de r es el increemento infinitesimal de ese vector). Para un desplazamiento pequeño diferencial, si multiplicamos F.dr e integramos entre el punto inicial (A) y final (B) ese es el trabajo de un campo de fuerza sobre la partícula de un punto a otro. 

Una partícula sobre la cual no se ejerce ninguna fuerza no se acelera (2ª ley de Newton). 

Cuando la partícula se mueve de un punto a otro hay una pequeña variación infinitesimal (dr)

Si yo diferencio (es decir, veo como es esta magnitud cuando hay una variación infinetesimal). 

El incremento diferencial de la energía lo puedo obtener olvidándome con respecto a que estoy derivando. 

Derivada del primero por el primeoro sin derivar y derivada del segundo por el primero sin derivar. Pon

*** Campos de fuerzas conservativos

En cierto campos de fuerza, el trabajo no depende de la trayectoria que siga la partícula. En estos casos, se cumple que existe un campo escalar, que llamamos energía potencial E, tal que Fvect = -grad Epot. 

Para este tipo de campos de fuerza, por tanto, 

(insertar apuntes pizarra). 

**** Campo eléctrico como campo de fuerza conservativo: 

Si queremos calcular ahora el trabajo que realiza el campo de fuerza eléctrica (igual al campo y la carga que tenga la partícula). Si el campo electrico lo podemos escribir como el gradiente 


El campo total en un punto es la suma de la carga eléctrica de las cargas individuales. Para cada una 

(ver fotos de la pizrra) 

- Si el desplazamiento tiene exactamente la dirección radial, el campo E tendría el máximo valor (puesto que los dos vectores tendrían el mismo sentido): 
- Si el desplazamiento tiene dirección perpendicular, el campo E sería 0, el campo E tendría una contribución nula, puesto que el producto escalar sería 0. 

Al desplazarnos de un punto otro, 

(ver foto de la pizarra). 

POr tanto, al desplazarnos entre dos puntos, en el campo de las cargas eléctricas vamos a hablar del campo ecalar V (equivalente a Energía potencial). 

(ver foto de la pizarra).

Por tanto, si definimos el campo escalar V =.. se tiene que dv = -ke q/r2dr = -Edr 

Por tanto, para calcular el trabajo de la fuerza eléctrica, 

para el campo electrico que crea cada carga, podemos escribir la funcion escalar potencial electrico....

El potencial electrico entonces V (que nos ha aparecido analizando una carga electrica en concreto), da lugar a un potencial electrico total, 


Recapitulando, para F conservativa... 


Podemos pensar en superficies en las que el potencial eléctrico es constante. 


(ver pizarar). 

Para una pa de una partícula cargada bajo la acción de un campo eléctrico 

V: potencial que crea el resto de cargas que hay en el espacio. 
PAra calcular el potencial, si tenemos varis, sería igual al sumatorio de las cargas. 
Si tuvieramos una distribución de cargas, tendríamos que integrar. 
Si tuvieramos un volumen integraríasmo sobre el volumen .... 


$x^2$

$x=\sqrt{b}$


\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures
\end{equation}                          % etc

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].


Gustavo resuleve el ejercicio. 


Ejercicio 2.2 

Desde el punto de vista físico, hay que saber que hay que calcular el potencial según 

$V=\in_A^B k_e \frac{\lambda dl}{r} = $ 

Matemáticamente, vamos a ver a qué es igual a cada parte. Vamos a ver si puedo integrar en función de la variable x. Intentemos escribir r y dl en funcion d el variable x. 

La distancia r al origen es muy facil, sería $r=\sqrt(x^2+y^2)=\sqrt(x^2+((\frac{a}{x})^2 $

Y el diferencial de longitud, viene dado por $dl=\sqrt(dx^2+dy^2)=\sqrt(dx^2(1+dy/dx^2)=$

$y^{'}=\frac{dx}{dy} = \frac{d}{x}\frac{a^2}{x}=-\frac{a^2}{x^2}$

$V= \int_{x=a}^{x=2a} k_e\frac{\lambda dx \sqrt (1+\frac{-a^2}{x^2}}){\sqrt(x^2+(\frac{a^2}{x})^2}$


Siguiente clase 

*** Ejemplo: Potencial eléctrico V que varía linealmente entre dos planos separados por una distancia d. 



Conocemos el potencial eléctrico V y queremos calcular el campo eléctrico (E = -grad V)

Ejempplo: Tenemos dos planos en los que conocemos el potencial eléctrico (V2>V1, por lo que aumenta linearmente en la cordneada z) 

___________________ $V_2$  

___________________ $V_1$

1. Escribimos el potencial 

$V = V_1 + \frac{V2-V1}{d} z 

Caclculamos el campo eléctrico 

$\vec{E} =-\vec{grad} V = - \lgroup \frac{\partial V }{\partial x} \hat{u_x} + \frac{\partial V }{\partial y} \hat{u_y} + \frac{\partial V }{\partial z} \hat{u_z}  \rgroup =  - \lgroup 0 + \frac{\partial V }{\partial z} \hat{u_z}  = -\frac{\partial  }{\partial z} \lgroup V_1 +  \frac{V_2 - V_1 }{d}z \hat{u_z}  = - \frac{V_2 - V_1 }\hat{u_z}$

Podemos preguntarnos, ¿qué ocurriría con una cierta partícula cargada que pusiéramos en el esapcio entre los planos? 
¿Seríais capaz de calcular como varia la velocidad de la partícula al pasar del punto A al B, de masa mp y carga qp, partiendo del reposo? 

Al ser un campo eléctrico conservativo, 

$E_c + E_p = constante $ 

$\Delta E_c = - \Delta E_p$ 

$E_{c,B}-E_{c,A} = -(E_{p,B}-E_{p,A})$

$1/2 m_p v_B^2 - 1/2 m 0^2 = - (q_p V_B - q_p V_A) $

$v_b = \sqrt (\frac{2}{m_p} (q_p V_a - q_p V_B) ) = \sqrt (\frac{2 q_p}{m_p} (V_a - V_B) ) = \sqrt (\frac{2 q_p}{m_p} \frac{(V_2 - V_1)}{d}l)  $

$V_A-V_B = (V_1 + \frac{V_2 -V_1}{d} z_A) - (V_1 + \frac{V_2 -V_1}{d} z_B) = \frac{V_2 - V_1}{d}l $

Esto es lo que encontramos cuando tenemos dos conductores (le llamamos un condensador)

$\vec{F} = q_p\vec{E} $ 

$m\vec{a} =\vec{F} =  q_p\vec{E} $ 


** Gradiente de $\vec{E}$ en casos de interés

*** (a) Si $\rho$ solo dpende de z 

$E(z) = E_z (z) \hat{u_z}$

$E = - \vec{grad} (V) = - \frac{\partial V(z)}{\partial z} \hat{u_z} $ 

El campo eléctrico $\vec{E}$ sólo tiene componente según z, $V$ solo puede depender de z, $V(z) 



*** (b) Distribución de carga con simetría esférica: $\rho$ solo depende de $r$:

El campo eléctrico es perpendicular a las superficies en las que V es constante (i.e. superficies esféricas). 

$\vec{E} = E_(r) \hat{u_r}$ 

$E = - \vec{grad} (V) = - \frac{\partial V}{\partial zr} \hat{u_r} $ 


*** (c) Distribución de carga con eje de simetría de revolución, $\rho$ sólo dpende de la distancia $r$ al eje 


$\vec{E} = E(r) \hat{u_r} = -\vec{grad} (V) = - \frac{\partial V}{\partial r} \hat{u_r} $ 

El potencial $V$ sólo depende de la distancia r 


** Cálculo del potencial V a partir del campo eléctrico $\vec{E}$

Lo que varía cualquier función escalar es su gradiente multipiplicaod por su vector de posición . Podemos ver fácilmente cuál es la diferencia de potencial entre dos campos cualesquiera basándonos en esta expresión diferencial. 

$\vec{E} = -\vec{grad} (V)$ 

$dV = \vec{grad} (V) \cdot \vec{d}r  = \vec{E} \cdot  \vec{d}r $ 

Entre dos puntos A y B, el potencial 

$V_B - V_A = \int_A^B dV = \int_A^B - \vec{E} \cdot  \vec{d}r  $

Paréntesis, hemos visto que para una carga puntal q: 

$V = k_e \frac{q}{r} = \frac{1}{4 \pi \epsilon_0} \frac{q}{r} $ 

Luego 

En el caso de distribución de carga de tañao finito, al ser V=0 en $\inf$: 

$V_P = V_P - 0 = \int_{\inf}^P \vec{E} \cdot  \vec{d}r  $

En este caso, 

$V_B - V_A = \int_A ^B -\vec{E} \cdot \vec{d}r  $ 

**** Ejemplo: recta uniformemente cargada con densidad lineal $\lambda$ 

No podemos decir que la recta tiene un potencial 0 en el infinito, porque la recta llega hasta el inifnito. 

Puedo calcular la diferencial de potencial entre los puntos a la distancia $r_a$ y $r_b$

$\vec{E} = \frac{\lambda}{2 \pi \epsilon_0 r \hat{u_r}} = $ 

= \int_A^B = -\frac{\lambda}{2 \pi \epsilon_0 r} dr = -\frac{\lambda}{2 \pi \epsilon_0 r} \int_A^B \frac{dr}{r} = \frac{\lambda}{2 \pi \epsilon_0 r} ln r _{r_A}^{r_B} =$ 

$= -\frac{\lambda}{2 \pi \epsilon_0 r} (ln (r_b) - ln (r_a)) = - \frac{\lambda}{2 \pi \epsilon_0 r} ln (\frac{r_B}{r_A})


**** Ejemplo: Esfera uniformemente cargada, con densidad de carga volumétrica $\rho$, de radio R 

¿Cómo calcular la diferencia de potencial entre varios puntos?

Aquí sí podemos tomar como origen de potenciales el infinito V = 0 (la carga está contenida en un volumen).  

$V_p = int_{inf}^P - \vec{E} \cdot \vec{dr} $ 

Hemos obtenido que 

$E = \frac{1}{4 \pi \epsilon _0} \frac{4/3 \pi \R^3 \rho}{r^2} \hat{u_r} $ si r>R

$E = \frac{\rho r}{3 \epsilon_0}\hat{u_r} $ si r<=R

Para puntos en los que $r_p>R$, 

(completar ecuaciones via fotos) 

Para los puntos de la esfera $V_p = R$, 

(completar ecuaciones via fotos) 

Para puntos dentro de la esfera, con $r_p > R$, 

(completar ecuaciones via fotos) 

Si pintamos entonces el varlor del potencial en función de la distancia (V s r)

(completar dibujo de clase)



**** Ejemplo: Comparación entre la fuerze electrostática y gravitatoria 

Ejemplo de Feynmann: si ponemos a dos personas a medio metro de distancia. Si retiramos un 1% de los electrones de las personas (se quedan cargadas las personas). La fuerza electrostatica que aparece entre ellas es la misma que experimentaria una masa tan grande como toda la masa del planeta concentradada?  

Vamos a aproximar las dos personas a dos cargas puntuales para usar la ley de Couloumb 

$F_e = k_e \frac{qq}{r^2}$ 

$F_m = M g$ 

¿Cómo estimar las cargas? 65% del cuerpo es 0, x % N, etc. ¿Donde esta la masa en los atomos? 

Queremos estimar el numero de protonoes que hay en el cuerpo para estimar que el 1% es lo que quitamos. Hay un poquito mas de protones (por el H) asumiendo que hay el mismo numero de protones que electrones. 

La mitad de la masa del cuerpo son protones: 

$1/2 80 kg \frac{1 prot}{1.673 10^{-27} kg 0.01 \frac{1.6 10^{-19}}{electron}} = 4 10^7 C$ 

¿Cuál sería la fuerza eléctrica? 

$F_e = \frac{9 10^9 Nm^2}{C^2} \frac{(4 0^7 C)^2}{(0.5 m)^2} = 5 10^25 N $

$F_g = M g = 6 \cdot 10^24 kg  \cdot  9.8 m/s^2 = 6  \cdot  10^25 N $

Para masas pequeñas, la importancia es la fuerza electrica. 


**** Ejercicio 2.3 

¿Qué campo total resulta en los puntos donde se intercruzan las dos esferas? 

Podemos calcular el campo que produce una esfera, el que produce la otra y como en la zona intermedia la contribución de las cargas se anula, no se tiene en cuenta. 

$\vec{E} = \int \int \int k_e \frac{\rho \d Vol}{r^2} \hat{u_r}



No se podría usar el teoerema de Gauss porque no hay una superficie en la que el E sea igual en todos los puntos. 

*  Temas 3 Electrostática en materiales conductores

Hasta ahora hemos estado hablando de interacciones de cargas en el vacío y ahora pasaremos a hablar de qué ocurre en los materiales. 

Hablaremos en el tema 3 de Materiales que son buenos conductores 

Hablaremos en el tema 4 de Materiales que son malos conductores 


Un material es conductor cuando contiene cargas libres que pueden moverse con gran facilidad. 

Si aparece un campo electrico las cargas se van a desplazar. ¿Cuando se va a alcanzar el equilibrio? Nos imaginamos un vaso de agua con cargas positivas y negativas. Lo que pasa es que los atomos van a tender a acumularse en los extremos. El resultado es que esa cargas producen un campo que van dsde las positivas hasta las negativas. El conjunto de iones produce un campo, que sumado al campo E introducido, debe suceder que en equilibrio cesa el movimiento de iones. Que signifca el equilibrio? Que esos dos campos son iguales (El E tot =0).  Mientras no sean cero los iones se van desplazando. 

La distribución con sales es un ejemplo muy claro. Nuestro propio cuerpo es un gran ejeplo de material conductor. El cuerpo humano puede conducir bastante bien la correinte electrica. Y si hay un campo electrico se mueven los iones. Podemos medir como de conductor es nuestro cuerpo. La piel es un buen aislante que esta seca. Cuando la piel es seca nos aisla. CUando la piel está mojada, nos volvemos muy buenos conductores de la electricida. 

Otro ejemplo son los materiales metalicos cuando uno habla de conductores. Los materiales metalicos: tenemos una red cristalina , en la mayoría encontrais granos, y hay un conjunto de electrones que puede moverse con mucha facilidad. Las particulas cargadas que se mueven en el caso de los metales son 

¿Qué pasa cuando se alcanza la situación de equilibrio en los metales? 

Vamos a fijarnos en las características de un material conductor en equilibrio eléctrico 

Lo primero que ocurre es que en el equilibrio el campo es 0 

(a) En equlibio, E_interior = 0 en todo el volumen . Si no fuera nulo continuaria el movimeinto de las cargas libres en el voolumen)

(b) Que ocurre con el potencial electrico si el campo E es constante. Es constante porque el E es -grad del potencial tiene que ser 0. Podría ser no nulo. 

(c) ¿Como puede ser entonces la densidad de carga por ud de volumen $\rho_{int}$? Necesariamente tiene que ser 0 por el hecho de que el campo electrico es 0 es el siguiente. Una forma de razonarlo es que al ser el campo electrico igual a 0, si aplicamos el tereoma de Gauss que nos dice que el flujo del campo E para cualquier superficie cerrada debe ser igual a la carga contenida por dentro partido por epsilo 0, el teorema de gauss se cumple para cualquier superficie que consideremos.  

¿Cual es la unica forma de garantizar que para cualquier superficie que cojamos, siempre la carga interior tiene que ser igual a 0? . Imaginemos que tenemos una region del espacio en la que la carga sea posisitva. En ese caso podríamos dibujar una superficie de gauss que no cumpliera la condición de 0. Por tanto no puede haber ning

En la aproximacion de medio continuo lo que vemos es que la carga por unidad de volumen es nula. 


*** Ejemplo: campo eléctrico en la superficie del conductor 

Puesto que dentro del conductor el potencial eléctrico es constnate, automáticamente sabemos que el campo elécticro ha de ser perpendicular a la superficie equipotencial. 

La superficie del condutor en equilibrio es de hecho una superficie equpotencial. 


Clase del 3 de octubre de 2022 

En este tema hemos estado estudiando qué ocurre con los materiales cuando están en equilibrio. Las cargas se distribuyen de forma que la .. es nulo. Hemos hablado de dos condensadores separados por un espacio no conductor (el vacío). En el último día hablamos de la capacidad de un condensador. Hoy hablaremos de qué ocurre cuando unimos varios condensadores. Y acabaremos con ejemplos. 

** Capacidad de un condensador 

La placa a mayor potencial tendrá una carga positiva y la placa a menor potencial tendrán una caga negativa. En la última clase habíamos comprobado que la capacidad para un condensador de placas paralelas es: 

A cada una de las placas de los condensadores se le suele llamar armadura. 

$ Q = C (V^+ - V^-) $ 

$C = \frac{\epsilon_0 A}{d}

Para hacer el cálculo habíamos visto cómo es el campo eléctrico dentro del conductor: homogéneo en el interior del conductor. 

A veces nos interesa combinar varios condensadores, entonces vamos a ver cuál es la re

** Asociación de condensadores 

*** En paralelo

Queremos calcular la carga resultante y el campo resultante. 

(poner dibujo de asociación de condensadores en paralelo). 

En el equlibrio, todas las armaduras de arriba estarían a un potencial V+ y las de abajo a V-. Igual diferencia de potencial para todos ellos. Así que la carga que aparece en cada uno de ellos será la carga multiplicada por la diferencia de potencial : 

Si nos preocupamos del condensador iésimo: 

$Q_1 = C_1 (V^+ - V^-) $ 


Carga total: 

$Q_{tot} = C_1 (V^+ - V^-) + ...+ C_i(V^+ - V^-)+C_N(V^+ - V^-)= (V^+ - V^-) \sum_{i=1}^{N} C_i $ 

En este caso la relación entre la carga total $Q_{tot}$ del conjunto y la diferencia de potencial es: 

$ Q_{tot} = \sum_{i=1}^{N} C_i (V^+ - V^-)$, 

donde $\sum_{i=1}^{N}$ es la carag equivalente $C_{equivalente}$ Un condensador que tuviera esa capacidad se comportaría igual. Estamos pensando en las cargas en equilibrio, no nos preocupamos de lo rápido o lento que sea el proceso de equilibrio (si los cables tienen resistencia etc).  La capacidad equivalente es la suma de las capacidades. 

*** En serie 

(poner dibujo de clase) 

Para entender qué ocurre en este caso, partiendo de la situación inicial de descarga y luego se conecta a una bateria (diferencia de potencial en los extremos). ¿Qué ocurre al conectar la diferencia de potencial? Redistribución de cargas a causa de la bateria. HAY UN FLUJO DE CARGA. Sabemos que en cada armadura habrá una carga, positiva en una de las placas y negativa en las otras. Si en un condensador aparece carga en una armadura, han llegado electrones a una placa (que salen de la placa de abajo). En cualquier caso para dos condensadores consecutivos las cargas son iguales. Lo que sale de uno sale de la otra. 

La carga es la misma en todos los condensadores. En cada condensador habrá una cierta diferencia de potencial 

$\Delta V_1 + Delta V_2+ ...+Delta V_n =V^+ - V^-$ .  

$\Delta V_1 + Delta V_2+ ...+Delta V_n =V^+ - V^-$ .  

completar fórmulas. 

Ejemplos de condensadores en serie y en paralelo. 

** Energía electrostática para una distribución cualquiera de cargas

Si tenemos una carga puntual Q y otra que se mueve de un punto a otro, la carga Q produce un campo elecetrico que cambia de un punto a otro y cuando la carga q se mueve de un punto a otro punto al cambiar de lugar hay una variación de energía potencial. Para colocar una serie de cargas en el espacio necesitamos realizar un trabajo para oponernos a una repulsion. Si son cargas negativas que se atraen, para acercarlas neceistamos realiar un trabajo. 

Copiar fórmulas 

*Energía almacenada en un condensador 

(copiar formulas)

Para terminar la clase vamos a hacar algunos comentarios. Hemos visto que los materiales buenos conductores tenemos cargas libres que pueden moverse con movilidad (por ejemplo en los metales, donde hay electrones libres). El campo electrico dentro del material es nulo. 

Puede haber una distrbución de cargas. En los modelos que utilizamos de medio continuo vemos 

SI el conductor de arriba tiene un cierto potencial mas pequeñito que el de arriba. Podriamos ver como son los electrones acelerados en funcion de como es el E. Esa 

Ejemplo: desfibrilidadores. Almacenan energia electrica a partir de condensadores. 

Ejemplo: celulas marcapasos. Si dan lugar a señales que no siguen un corden concreto se produce el fenomeno de fibrilacion. Una posibildiad para recuperar la contraccion periodica (contraccion al unisono de las celulas). 
